name: check-build

on:
  pull_request

jobs:
  check-build:
    runs-on: ubuntu-20.04
    steps:
    - name: update
      run: sudo apt-get -y update
    - name: setup
      run: python3 setup.py install
    - name: install pytest-cov
      run: pip install pytest-cov
    - name: install
      run: pip install .[ja]
    - name: pytest
      run: python3 -m pytest
    - name: test
      run: ./test.sh
